import Handlebars from 'handlebars'

export class TemplateService {

    constructor() {
        // Register helpers if needed
        Handlebars.registerHelper('formatDate', (date) => {
            return new Date(date).toLocaleDateString()
        })
        Handlebars.registerHelper('formatCurrency', (amount) => {
            return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(amount)
        })
    }

    validateVariables(templateSchema: Record<string, { type: string, label: string }>, variables: Record<string, any>): string[] {
        const missing = []
        for (const key of Object.keys(templateSchema)) {
            if (variables[key] === undefined || variables[key] === null || variables[key] === '') {
                missing.push(templateSchema[key].label || key)
            }
        }
        return missing
    }

    render(templateContent: string, variables: Record<string, any>): string {
        // Basic XSS sanitization could go here, but for Offers generated by Admins, we assume trust.
        // However, we should still escape user input if it comes from external sources.
        // Handlebars escapes by default unless {{{ }}} is used.

        const template = Handlebars.compile(templateContent)
        return template(variables)
    }

    extractVariables(content: string): string[] {
        // Regex to find {{variable}}
        const regex = /{{(.*?)}}/g;
        const matches = [];
        let match;
        while ((match = regex.exec(content)) !== null) {
            matches.push(match[1]);
        }
        return [...new Set(matches)]; // Unique
    }
}

export const templateService = new TemplateService()
